version: "3.4"

services:
  accountservice:
    image: mrudb/accountservice:latest
    build:
      context: ./Services/AccountService
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      storenetwork:
        ipv4_address: 172.20.10.101

  inventoryservice:
    image: mrudb/inventoryservice:latest
    build:
      context: ./Services/InventoryService
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      storenetwork:
        ipv4_address: 172.20.10.102

  shoppingservice:
    image: mrudb/shoppingservice:latest
    build:
      context: ./Services/ShoppingService
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      storenetwork:
        ipv4_address: 172.20.10.103

  store:
    image: mrudb/store:latest
    environment:
      ACCOUNT_SERVICE_API_BASE: http://172.20.10.101/api
      INVENTORY_SERVICE_API_BASE: http://172.20.10.102/api
      SHOPPING_SERVICE_API_BASE: http://172.20.10.103/api
    build:
      context: ./Store
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      storenetwork:
        ipv4_address: 172.20.10.100

networks:
  storenetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

